[package]
name = "adventofcode2020"
edition = '2018'
version = "1.0.0"
authors = ["liyuntao <liyuntao58607@gmail.com>"]

[dependencies]
chrono = "0.4.6"
lazy_static = "1.2.0"
regex = "1"
#z3 = "0.3.0"